<?php

namespace CatalogueBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByName(){
          $qb = $this->createQueryBuilder('c')
                ->select('c.name, c.id')
                ->where('c.isActive = 1');
//                ->join('prof.personnel','p');
         return $qb
            ->getQuery()
            ->getResult()
          ;
    }
}
